language: node_js
node_js:
  - '10'
stages:
  - name: lint and test
  - publish: deploy stage

jobs:
  include:
    - stage: lint and test
      name: lint
      script:
        - lerna bootstrap
        - yarn lint
    - script:
        - lerna bootstrap
        - yarn test
      name: test
    - stage: deploy stage
      name: deploy stage [name]
      script:
        - lerna bootstrap
        - yarn build
        - ls ./packages/common
