language: node_js
node_js: "12.16"

notifications:
  email:
    on_success: never
    on_failure: always

cache: yarn

jobs:
  include:
    # - stage: test
    #   script:
    #     - lerna bootstrap
    #     - lerna run build
    #     - lerna run test
    - stage: dev build and deploy
      if: branch = dev
      script:
        - lerna bootstrap
        - lerna run build
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        script: "lerna publish --dist-tag next --canary --preid next --yes"
        skip_cleanup: true
        on:
          all_branches: true
    - stage: build and deploy
      if: tag IS present
      script:
        - lerna bootstrap
        - lerna run build
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        script: "lerna publish from-git --yes"
        skip_cleanup: true
        on:
          tags: true