language: node_js
node_js:
  - '10'
# stages:
#   - name: lint and test
#   - publish: deploy stage

jobs:
  include:
    - stage: "beta release"
      if: branch = master
      node_js: '10'
      script:
        - lerna bootstrap
        - lerna run build
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - lerna publish from-git --yes --dist-tag beta

    - stage: "release"
      if: tag IS present
      node_js: '10'
      script:
        - lerna bootstrap
        - lerna run build
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - lerna publish from-git --yes --dist-tag beta
