language: node_js
node_js:
  - '10'
# stages:
#   - name: lint and test
#   - publish: deploy stage

jobs:
  include:
    # - stage: lint and test
    #   name: lint
    #   before_script:
    #     - echo $NPM_TOKEN
    #   script:
    #     - lerna bootstrap
    #     - yarn lint
    # - script:
    #     - lerna bootstrap
    #     - yarn test
    #   name: test
    - stage: deploy stage
      name: deploy stage [name]
      script:
        - lerna bootstrap
        - yarn build
      before_deploy:
        - cat ./packages/common/dist/index.js
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        script: 'yarn run publish'
        skip_cleanup: true
        on:
          node: '10'
          tags: true
    - stage: deploy stage
      name: deploy stage [name]
      script:
        - lerna bootstrap
        - yarn build
      before_deploy:
        - cat ./packages/common/dist/index.js
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        script: 'yarn run publish:canary'
        skip_cleanup: true
        on:
          node: '10'
          all_branches: true
